#!/usr/bin/env python3
"""Inject generated TEXT_SEGMENTS into src/Typewriter.tsx."""

from __future__ import annotations

import ast
import math
import re
import shutil
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
SEGMENTS_PATH = SCRIPT_DIR / "work" / "segments.ts"
TARGET_PATH = SCRIPT_DIR / "src" / "Typewriter.tsx"
BACKUP_PATH = SCRIPT_DIR / "src" / "Typewriter.tsx.bak"
ROOT_PATH = SCRIPT_DIR / "src" / "Root.tsx"
ROOT_BACKUP_PATH = SCRIPT_DIR / "src" / "Root.tsx.bak"

TEXT_SEGMENTS_RE = re.compile(
    r"^(?:// Generated by .*?\n)*(?:export\s+)?const\s+TEXT_SEGMENTS\s*:\s*TextSegment\[\]\s*=\s*\[.*?^\];",
    re.MULTILINE | re.DOTALL,
)
DURATION_RE = re.compile(r"^const\s+DURATION_SECONDS\s*=\s*([0-9.]+);", re.MULTILINE)
OBJECT_RE = re.compile(r"\{([^{}]+)\}", re.DOTALL)
FIELD_RE = {
    "text": re.compile(r"""text\s*:\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')"""),
    "mode": re.compile(r"""mode\s*:\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')"""),
    "delayFrames": re.compile(r"delayFrames\s*:\s*(-?\d+)"),
    "ghostText": re.compile(r"""ghostText\s*:\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')"""),
    "strikeText": re.compile(r"""strikeText\s*:\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')"""),
}
MODE_SPEED = {"burst": 2, "normal": 3, "deliberate": 5, "thinking": 2}
TAIL_FRAMES = 60


def fail(message: str, code: int = 1) -> None:
    print(f"Error: {message}", file=sys.stderr)
    raise SystemExit(code)


def count_segments(source: str) -> int:
    return len(re.findall(r"\{\s*text\s*:", source))


def decode_literal(value: str) -> str:
    try:
        return str(ast.literal_eval(value))
    except (SyntaxError, ValueError) as exc:
        fail(f"invalid string literal in segments.ts: {exc}")


def estimate_duration_seconds(source: str) -> float:
    final_frame = 0
    found = False
    for match in OBJECT_RE.finditer(source):
        body = match.group(1)
        text_match = FIELD_RE["text"].search(body)
        mode_match = FIELD_RE["mode"].search(body)
        delay_match = FIELD_RE["delayFrames"].search(body)
        if not (text_match and mode_match and delay_match):
            continue
        found = True
        text = decode_literal(text_match.group(1))
        mode = decode_literal(mode_match.group(1))
        delay_frames = int(delay_match.group(1))
        typing_frames = len(text) * MODE_SPEED.get(mode, 2)
        ghost_match = FIELD_RE["ghostText"].search(body)
        strike_match = FIELD_RE["strikeText"].search(body)
        if ghost_match and decode_literal(ghost_match.group(1)):
            typing_frames += 32
        if strike_match:
            strike_text = decode_literal(strike_match.group(1))
            if strike_text:
                typing_frames += len(strike_text) * 2 + 32
        final_frame = max(final_frame, max(0, delay_frames) + typing_frames)
    if not found:
        fail("could not estimate duration; no valid segments found in segments.ts.")
    return math.ceil((final_frame + TAIL_FRAMES) / 29.97)


def update_duration_from_segments(source: str) -> float:
    if not ROOT_PATH.exists():
        fail(f"missing Root.tsx for duration update: {ROOT_PATH}")

    root = ROOT_PATH.read_text(encoding="utf-8")
    if not DURATION_RE.search(root):
        fail("DURATION_SECONDS declaration not found in src/Root.tsx.")
    duration = estimate_duration_seconds(source)
    updated = DURATION_RE.sub(f"const DURATION_SECONDS = {duration:g};", root, count=1)
    shutil.copy2(ROOT_PATH, ROOT_BACKUP_PATH)
    ROOT_PATH.write_text(updated, encoding="utf-8")
    return duration


def main() -> int:
    if not SEGMENTS_PATH.exists():
        fail(f"missing generated segments file: {SEGMENTS_PATH}")
    if not TARGET_PATH.exists():
        fail(f"missing target file: {TARGET_PATH}")

    replacement = SEGMENTS_PATH.read_text(encoding="utf-8").strip() + "\n"
    if not TEXT_SEGMENTS_RE.search(replacement):
        fail("segments.ts does not contain a complete TEXT_SEGMENTS block.")

    target = TARGET_PATH.read_text(encoding="utf-8")
    match = TEXT_SEGMENTS_RE.search(target)
    if not match:
        fail("TEXT_SEGMENTS block not found; src/Typewriter.tsx was not modified.")

    updated = target[: match.start()] + replacement + target[match.end() :]

    shutil.copy2(TARGET_PATH, BACKUP_PATH)
    TARGET_PATH.write_text(updated, encoding="utf-8")

    print(f"Injected {count_segments(replacement)} segments into src/Typewriter.tsx")
    duration = update_duration_from_segments(replacement)
    print(f"Updated src/Root.tsx duration to {duration:g}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
