#!/usr/bin/env python3
"""Inject generated TEXT_SEGMENTS into src/Typewriter.tsx."""

from __future__ import annotations

import argparse
import ast
import math
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path


TEXT_SEGMENTS_RE = re.compile(
    r"^(?:// Generated by .*?\n)*(?:export\s+)?const\s+TEXT_SEGMENTS\s*:\s*TextSegment\[\]\s*=\s*\[.*?^\];",
    re.MULTILINE | re.DOTALL,
)
DURATION_RE = re.compile(r"^const\s+DURATION_SECONDS\s*=\s*([0-9.]+);", re.MULTILINE)
OBJECT_RE = re.compile(r"\{([^{}]+)\}", re.DOTALL)
FIELD_RE = {
    "text": re.compile(r"""text\s*:\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')"""),
    "mode": re.compile(r"""mode\s*:\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')"""),
    "delayFrames": re.compile(r"delayFrames\s*:\s*(-?\d+)"),
    "ghostText": re.compile(r"""ghostText\s*:\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')"""),
    "strikeText": re.compile(r"""strikeText\s*:\s*("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')"""),
}
MODE_SPEED = {"burst": 2, "normal": 3, "deliberate": 5, "thinking": 2}
TAIL_FRAMES = 60


@dataclass
class ProjectPaths:
    segments: Path
    target: Path
    target_backup: Path
    root: Path
    root_backup: Path

    @classmethod
    def from_project_dir(cls, project_dir: Path) -> "ProjectPaths":
        return cls(
            segments=project_dir / "work" / "segments.ts",
            target=project_dir / "src" / "Typewriter.tsx",
            target_backup=project_dir / "src" / "Typewriter.tsx.bak",
            root=project_dir / "src" / "Root.tsx",
            root_backup=project_dir / "src" / "Root.tsx.bak",
        )


def fail(message: str, code: int = 1) -> None:
    print(f"Error: {message}", file=sys.stderr)
    raise SystemExit(code)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Inject generated TEXT_SEGMENTS into a typewriter-video project's src/Typewriter.tsx.",
    )
    parser.add_argument(
        "--project-dir",
        default=".",
        help=(
            "Target Remotion project directory. Reads "
            "<project-dir>/work/segments.ts and rewrites <project-dir>/src/Typewriter.tsx "
            "and <project-dir>/src/Root.tsx (with .bak backups). "
            "Default: current working directory."
        ),
    )
    return parser.parse_args()


def count_segments(source: str) -> int:
    return len(re.findall(r"\{\s*text\s*:", source))


def decode_literal(value: str) -> str:
    try:
        return str(ast.literal_eval(value))
    except (SyntaxError, ValueError) as exc:
        fail(f"invalid string literal in segments.ts: {exc}")


def estimate_duration_seconds(source: str) -> float:
    final_frame = 0
    found = False
    for match in OBJECT_RE.finditer(source):
        body = match.group(1)
        text_match = FIELD_RE["text"].search(body)
        mode_match = FIELD_RE["mode"].search(body)
        delay_match = FIELD_RE["delayFrames"].search(body)
        if not (text_match and mode_match and delay_match):
            continue
        found = True
        text = decode_literal(text_match.group(1))
        mode = decode_literal(mode_match.group(1))
        delay_frames = int(delay_match.group(1))
        typing_frames = len(text) * MODE_SPEED.get(mode, 2)
        ghost_match = FIELD_RE["ghostText"].search(body)
        strike_match = FIELD_RE["strikeText"].search(body)
        if ghost_match and decode_literal(ghost_match.group(1)):
            typing_frames += 32
        if strike_match:
            strike_text = decode_literal(strike_match.group(1))
            if strike_text:
                typing_frames += len(strike_text) * 2 + 32
        final_frame = max(final_frame, max(0, delay_frames) + typing_frames)
    if not found:
        fail("could not estimate duration; no valid segments found in segments.ts.")
    return math.ceil((final_frame + TAIL_FRAMES) / 29.97)


def update_duration_from_segments(source: str, paths: ProjectPaths) -> float:
    if not paths.root.exists():
        fail(f"missing Root.tsx for duration update: {paths.root}")

    root = paths.root.read_text(encoding="utf-8")
    if not DURATION_RE.search(root):
        fail("DURATION_SECONDS declaration not found in src/Root.tsx.")
    duration = estimate_duration_seconds(source)
    updated = DURATION_RE.sub(f"const DURATION_SECONDS = {duration:g};", root, count=1)
    shutil.copy2(paths.root, paths.root_backup)
    paths.root.write_text(updated, encoding="utf-8")
    return duration


def main() -> int:
    args = parse_args()
    project_dir = Path(args.project_dir).expanduser().resolve()
    paths = ProjectPaths.from_project_dir(project_dir)

    if not paths.segments.exists():
        fail(f"missing generated segments file: {paths.segments}")
    if not paths.target.exists():
        fail(f"missing target file: {paths.target}")

    replacement = paths.segments.read_text(encoding="utf-8").strip() + "\n"
    if not TEXT_SEGMENTS_RE.search(replacement):
        fail("segments.ts does not contain a complete TEXT_SEGMENTS block.")

    target = paths.target.read_text(encoding="utf-8")
    match = TEXT_SEGMENTS_RE.search(target)
    if not match:
        fail("TEXT_SEGMENTS block not found; src/Typewriter.tsx was not modified.")

    updated = target[: match.start()] + replacement + target[match.end() :]

    shutil.copy2(paths.target, paths.target_backup)
    paths.target.write_text(updated, encoding="utf-8")

    print(f"Injected {count_segments(replacement)} segments into {paths.target}")
    duration = update_duration_from_segments(replacement, paths)
    print(f"Updated {paths.root} duration to {duration:g}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
